# version: "3.8"
name: "fastapi"
services:
  api:
    build:
      context: ./
      dockerfile: "Dockerfile"
    depends_on:
      - postgres_db
    ports:  
      - "8000:8000" 
    networks:
      - my-api-net

  postgress_db:
    image: postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sweethomealabama
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net  # Ensure there's a space before "my-api-net"

volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:
